### ISSUE TITLE
Record audio from microphone

### ISSUE THREAD

**Issue by brianchirls** [datavized/puppets#13]
- [x] Open mic with `getUserMedia` (new `MediaDevices` API)
- [x] Record to memory (when record button #4 is pressed until recording stops)
- [x] Upload to server as .wav

@cvan do you know if we can save these to the Firebase account? Or do we need another server we can upload to?

@cvan Do you know if there's a server somewhere that can re-encode these files to AAC, vorbis and/or Opus? I'm not sure if we can reliably do that on the client without messing with a massive emscripten module.

**Comment by cvan** [comment]
@cvan yep, we can save static files to Firebase too :)

@brianchirls I'd use https://github.com/mido22/recordOpus or https://github.com/muaz-khan/RecordRTC/

**Comment by cvan** [comment]
I'd also check out https://webaudiodemos.appspot.com/AudioRecorder/index.html

**Comment by brianchirls** [comment]
@cvan FYI opus playback doesn't work in Safari or (I think?) Edge/IE. And it's broken in Chrome until at least mid-march release of v57. https://bugs.chromium.org/p/chromium/issues/detail?id=482934

**Comment by cvan** [comment]
I actually didn't know that Opus isn't supported in Safari. It seems [Edge is supported](http://caniuse.com/#search=opus).

Hmm, what exactly in https://bugs.chromium.org/p/chromium/issues/detail?id=482934 affects Opus playback? I've seen Opus work in Chromium; do you have examples that don't work?

**Comment by brianchirls** [comment]
@cvan The problem with Chrome is that you can't play Opus using Web Audio API - only in an `<audio>` element

**Comment by cvan** [comment]
Yikes, that's quite a big bug, especially considering that [Chromium](https://www.chromium.org/audio-video) doesn't support a whole bunch of proprietary codecs.
