### ISSUE TITLE
Storing puppet show state to server

### ISSUE THREAD

**Issue by brianchirls** [datavized/puppets#14]
For now, we're going to keep show state very simple, based on a single URL. CRUD, authentication, etc. will be listed under one or more separate issues and implemented as time allows.

- [x] All state will be stored in Firebase (see #4)
- [x] Load puppet show by URL
- [x] Create a new puppet show if none given in URL
- [x] "New" button for starting a new show from scratch
- [x] Erase files and data on reset?

For development purposes, there will be no authentication. Will have to discuss write permission design with @cvan and @caseyyee and make sure Firebase account is configured accordingly.

**Comment by brianchirls** [comment]
@cvan Have you guys thought about where this is going to be hosted? It will affect how we can form the URLs.

**Comment by cvan** [comment]
@brianchirls we'll host it on a Digital Ocean droplet: nginx, Ubuntu, LetsEncrypt, Cloudflare. I can set that all up in about 30 min - I can do it sometime next week.

**Comment by brianchirls** [comment]
@cvan Okay, if we can get it set up to do a catch-all 200 response, then we can not sure hashes in URLs and set an actual path with History API.

I'm using the key I get back from Firebase for now as the unique identifier for each puppet show recording. It's not ideal 'cause they're long, case sensitive and have dashes and underscores. But it's easy and (more or less) guaranteed not to collide.

Is there an easy deploy command/script for it that I can install as an npm dependency?

**Comment by cvan** [comment]
> @cvan Okay, if we can get it set up to do a catch-all 200 response, then we can not sure hashes in URLs and set an actual path with History API.

yeah, do you have a good page router you use? I have a few (that actually preserve scroll position, which so few seem to do, including the popular `react-router`).

> @cvan Okay, if we can get it set up to do a catch-all 200 response, then we can not sure hashes in URLs and set an actual path with History API.

we could let users just load up any URL and use that slug as the key.

we did something like that for https://github.com/etherworld/etherworld:

* https://etherworld.herokuapp.com/room/yolo
* https://etherworld.herokuapp.com/room/hello
* https://etherworld.herokuapp.com/room/house

> Is there an easy deploy command/script for it that I can install as an npm dependency?

I'll have it auto-deploy based on a GitHub Webhook, so any pushed commits to `master` (or a `prod` branch) deploy to the production (or staging) server. (I use a similar setup for my WebVR Agent. it's slick.)

**Comment by cvan** [comment]
Filed #15 for myself for early next week.

**Comment by brianchirls** [comment]
re: webhook - very cool. There's a build process, but I think I have some scripts that will let me easily check on a branch that's just for built output.

I don't need no router. It's not that complicated. I'm just parsing the URL with a regex and setting some state. And there's no scrolling.

**Comment by cvan** [comment]
yeah, any commands that need to be run, just put them in a `deploy` script

**Comment by cvan** [comment]
> I don't need no router. It's not that complicated. I'm just parsing the URL with a regex and setting some state. And there's no scrolling.

okay, sweet. I don't see any usage of `pushState` yet. (do any of the `npm` modules handle that?)
